name: IBM Cloud App Configuration Sync

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request are approved
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  updateConfig:
    runs-on: ubuntu-latest

    steps:
      - uses: jojustin/IBM-Cloud-App-Configuration-Sync@v0.1
        with:
          IBM_CLOUD_REGION: au-syd
          IBM_CLOUD_RESOURCE_GROUP: default
          CONFIG_FILE_NAME: 'appsettings.json'
      
